# Generated by Django 5.1.3 on 2024-11-18 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_grade_remove_chapter_grade_level_chapter_grade'),
        ('activities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityinstance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.chapter'),
        ),
        migrations.AddField(
            model_name='activityinstance',
            name='activity_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitymodel'),
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype'),
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='difficulty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.difficultylevel'),
        ),
        migrations.AddField(
            model_name='painpoint',
            name='activity_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activityinstance'),
        ),
        migrations.AddField(
            model_name='painpoint',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.method'),
        ),
        migrations.AddField(
            model_name='painpoint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
