# Generated by Django 5.1.3 on 2024-11-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymodel',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
