# Generated by Django 5.1.3 on 2024-11-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_grade_remove_chapter_grade_level_chapter_grade'),
        ('activities', '0003_activitymodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymodel',
            name='grade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='academics.grade'),
        ),
    ]
