# Generated by Django 5.1.3 on 2024-11-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activitymodel_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymodel',
            name='grade',
        ),
    ]
