# Generated by Django 5.1.3 on 2024-11-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_activitymodel_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymodel',
            name='svg_content',
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
