# Generated by Django 5.1.3 on 2024-11-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_chapter_id_chapter_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='method',
            old_name='chapter_id',
            new_name='chapter',
        ),
    ]
